library(dplyr)
library(stringr)

employers <- read.csv("employers.csv")

#employers$Employer <- str_replace_all(employers$Employer, "United Parcel Service Incorporated", "United Parcel Service Incorporated (UPS)")
# employers$Employer <- str_replace_all(employers$Employer, "Louisville Metro Government", "City Of Louisville")
# employers$Employer <- str_replace_all(employers$Employer, "A & R Logistics",  "A&R Logistics")
# employers$Employer <- str_replace_all(employers$Employer, "A & R Transport",  "A&R Logistics")
# employers$Employer <- str_replace_all(employers$Employer, "Aaa East Central", "AAA")
# employers$Employer <- str_replace_all(employers$Employer, "Aaa Motor Club",   "AAA")
# employers$Employer <- str_replace_all(employers$Employer, "Abc Supply Company Incorporated",   "Abc Supply")
# employers$Employer <- str_replace_all(employers$Employer, "Advance Ready Concrete Mix Co",   "Advance Ready Concrete")
# employers$Employer <- str_replace_all(employers$Employer, "Advanced Lifeline Services",   "Advanced Lifeline")
# employers$Employer <- str_replace_all(employers$Employer, "Advantage Sales & Marketing",  "Advantage Solutions")
# employers$Employer <- str_replace_all(employers$Employer, "Aeges Therapies",   "Aegis Therapies")
# employers$Employer <- str_replace_all(employers$Employer, "Aegis Therapies",                                 "TESTING123")
# employers$Employer <- str_replace_all(employers$Employer, "Aeg",                                             "AEG Worldwide")
# employers$Employer <- str_replace_all(employers$Employer, "TESTING123",                                      "Aegis Therapies")
# employers$Employer <- str_replace_all(employers$Employer, "American Health Network Incorporated",            "American Health Network")
# employers$Employer <- str_replace_all(employers$Employer, "American National Insurance Company",             "American National Insurance")
# employers$Employer <- str_replace_all(employers$Employer, "American National Insurance Property & Casualty", "American National Insurance")
# employers$Employer <- str_replace_all(employers$Employer, "American National Property & Casualty Company",   "American National Insurance")
# employers$Employer <- str_replace_all(employers$Employer, "Amerigas Propane",                        "Amerigas")
# employers$Employer <- str_replace_all(employers$Employer, "Anthem Insurance Company",                "Anthem Blue Cross")
# employers$Employer <- str_replace_all(employers$Employer, "Arthur Wright And Associa",               "Arthur Wright And Associates")
# employers$Employer <- str_replace_all(employers$Employer, "Arthur Wright And Associatestes",         "Arthur Wright And Associates")
# employers$Employer <- str_replace_all(employers$Employer, "Asset Controlservices",                   "Asset Control Services")
# employers$Employer <- str_replace_all(employers$Employer, "Atlantic Aviation Fbo Holdings Llc",      "Atlantic Aviation")
# employers$Employer <- str_replace_all(employers$Employer, "Atria Senior Living Group",               "Atria Senior Living")
# employers$Employer <- str_replace_all(employers$Employer, "Averitt Express",                         "Averitt")
# employers$Employer <- str_replace_all(employers$Employer, "Autoneum North America, Inc",             "Autoneum")
# employers$Employer <- str_replace_all(employers$Employer, "Axa Advisors",                            "Axa")
# employers$Employer <- str_replace_all(employers$Employer, "Babcock Power Incorporated",              "Babcock Power")
# employers$Employer <- str_replace_all(employers$Employer, "Badger Daylighting Corporation",          "Badger Daylight")
# employers$Employer <- str_replace_all(employers$Employer, "Bassett Furniture Industries",            "Bassett Home Furnishings")
# employers$Employer <- str_replace_all(employers$Employer, "Blue & Company Llc",                      "Blue & Company")
# employers$Employer <- str_replace_all(employers$Employer, "Atlas Transportation Incorporated",       "Atlas World Group Inc.")
# employers$Employer <- str_replace_all(employers$Employer, "Atlas World Group Incorporated",          "Atlas World Group Inc.")
# employers$Employer <- str_replace_all(employers$Employer, "Baptist Health & Baptist Health Paducah", "Baptist Health")
# employers$Employer <- str_replace_all(employers$Employer, "Baptist Health Kentucky",     "Baptist Health")
# employers$Employer <- str_replace_all(employers$Employer, "Baptist Health Lagrange",     "Baptist Health")
# employers$Employer <- str_replace_all(employers$Employer, "Baptist Health Louisville",   "Baptist Health")
# employers$Employer <- str_replace_all(employers$Employer, "Baptist Health Medical Group","Baptist Health")
# employers$Employer <- str_replace_all(employers$Employer, "Baptist Health Of Kentucky",  "Baptist Health")
# employers$Employer <- str_replace_all(employers$Employer, "Baptist Health Plan",         "Baptist Health")
# employers$Employer <- str_replace_all(employers$Employer, "Baptist Healthcare System",   "Baptist Health")
# employers$Employer <- str_replace_all(employers$Employer, "Baptist Healthlouisville",    "Baptist Health")
# employers$Employer <- str_replace_all(employers$Employer, "Baptist Hospital",            "Baptist Health")
# employers$Employer <- str_replace_all(employers$Employer, "Beacon Health Strategies",  "Beacon Health Options")
# employers$Employer <- str_replace_all(employers$Employer, "Beacon Roofing Supply",                "Beacon Roofing Supply Inc.")
# employers$Employer <- str_replace_all(employers$Employer, "Beacon Roofing Supply Inc. Incorporated",   "Beacon Roofing Supply Inc.")
# employers$Employer <- str_replace_all(employers$Employer, "Boyd Bros",   "Boyd Bros Transportation Inc.")
# employers$Employer <- str_replace_all(employers$Employer, "Boyd Bros Transportation Inc. Transportation Incorporated", "Boyd Bros Transportation Inc")
# employers$Employer <- str_replace_all(employers$Employer, "Boyd Bros Transportation Inc",   "Boyd Bros Transportation Inc.")
# employers$Employer <- str_replace_all(employers$Employer, "Boyd Bros Transportation Inc..",   "Boyd Bros Transportation Inc.")
# employers$Employer <- str_replace_all(employers$Employer, "Boyd Bros Transportation Incorporated",   "Boyd Bros Transportation Inc.")
# employers$Employer <- str_replace_all(employers$Employer, "Boyd Brothers",   "Boyd Bros Transportation Inc.")
# employers$Employer <- str_replace_all(employers$Employer, "Boyd Brothers Transportation",   "Boyd Bros Transportation Inc.")
# employers$Employer <- str_replace_all(employers$Employer, "Boyd Bros Transportation Inc. Transportation",   "Boyd Bros Transportation Inc.")
# employers$Employer <- str_replace_all(employers$Employer, "Boys And Girls Clubs Of Kentuckiana",   "Boys and Girls Club of Kentuckiana")
# employers$Employer <- str_replace_all(employers$Employer, "Boys And Girls Club Of Kentuckiana",   "Boys and Girls Club of Kentuckiana")
# employers$Employer <- str_replace_all(employers$Employer, "Bradley Consulting And Management",  "Bradley Consulting & Management")
# employers$Employer <- str_replace_all(employers$Employer, "Brinks Incorporated",   "Brinks")
# employers$Employer <- str_replace_all(employers$Employer, "Brookdale Incorporated",   "Brookdale Senior Living")
# employers$Employer <- str_replace_all(employers$Employer, "Buddy Mooretrucking", "Buddy Moore Trucking")
# employers$Employer <- str_replace_all(employers$Employer, "Builders Transportation Company, Llc",   "Builders Transportation Company")
# employers$Employer <- str_replace_all(employers$Employer, "Cadence Premier Global",   "Cadence Premier Logistics")
# employers$Employer <- str_replace_all(employers$Employer, "Cadence Premier Logistics / Tm Global Trans",   "Cadence Premier Logistics")
# employers$Employer <- str_replace_all(employers$Employer, "Cafepress",           "Cafepress Inc.")
# employers$Employer <- str_replace_all(employers$Employer, "Cafepress Inc",       "Cafepress Inc.")
# employers$Employer <- str_replace_all(employers$Employer, "Cafepress, Inc",      "Cafepress Inc.")
# employers$Employer <- str_replace_all(employers$Employer, "Cafepress Inc..",     "Cafepress Inc.")
# employers$Employer <- str_replace_all(employers$Employer, "Cafepress Inc.. Inc", "Cafepress Inc.")
# employers$Employer <- str_replace_all(employers$Employer, "Cafepress Inc.., Inc", "Cafepress Inc.")
# employers$Employer <- str_replace_all(employers$Employer, "Cafepress Inc. Inc",   "Cafepress Inc.")
# employers$Employer   <- str_replace_all(employers$Employer, "General Electric Company", "General Electric (GE)")
# employers$Employer   <- str_replace_all(employers$Employer, "Ge Appliance & Lighting",  "General Electric (GE)")
# employers$Employer   <- str_replace_all(employers$Employer, "Ge Appliance And Lighting","General Electric (GE)")
# employers$Employer   <- str_replace_all(employers$Employer, "Ge Appliances",            "General Electric (GE)")
# employers$Employer   <- str_replace_all(employers$Employer, "Ge Lighting",              "General Electric (GE)")
# employers$Employer   <- str_replace_all(employers$Employer, "Ge Healthcare Worldwide",  "GE Healthcare")
# employers$Employer   <- str_replace_all(employers$Employer, "Ge Healthcare",            "GE Healthcare")
# employers$Employer   <- str_replace_all(employers$Employer, "Deloitte", "Deloite")
# employers$Employer   <- str_replace_all(employers$Employer, "Deloite", "Delloite")
# employers$Employer   <- str_replace_all(employers$Employer, "H & Rblock",             "H&R Block")
# employers$Employer   <- str_replace_all(employers$Employer, "H And R Block Seasonal", "H&R Block")
employers$Employer   <- str_replace_all(employers$Employer, "Jp Morgan Chase",         "JPMorgan Chase")
employers$Employer   <- str_replace_all(employers$Employer, "JP Morgan Chase Company", "JPMorgan Chase")
employers$Employer   <- str_replace_all(employers$Employer, "", "")
employers$Employer   <- str_replace_all(employers$Employer, "", "")
employers$Employer   <- str_replace_all(employers$Employer, "", "")
employers$Employer   <- str_replace_all(employers$Employer, "", "")
employers$Employer   <- str_replace_all(employers$Employer, "", "")
employers$Employer   <- str_replace_all(employers$Employer, "", "")
employers$Employer   <- str_replace_all(employers$Employer, "", "")
employers$Employer   <- str_replace_all(employers$Employer, "", "")
employers$Employer   <- str_replace_all(employers$Employer, "", "")
employers$Employer   <- str_replace_all(employers$Employer, "", "")

test <- as.data.frame(unique(employers$Employer))


##Automotive TO Automotive Resources International
## Blue TO Blue & Company


#### SPECIAL CASE ... CITY OF LOUISVILLE
# louisville <- employers %>% filter(Employer == "Louisville")
# ## CHANGE TO CITY OF LOUISVILLE
# louisville$Employer <- str_replace_all(louisville$Employer, "Louisville", "City Of Louisville")
# ## FILTER MAIN DATA TO NOT INCLUDE EMPLOYER == LOUISVILLE
# employers <- employers %>% filter(Employer != "Louisville" & 
#                                   Employer != "Archdiocese Of Los Angeles")
# ## BIND LOUISVILLE DATA TO EMPLOYER MAIN DATA
# employers <- rbind(employers, louisville)
employersList <- as.data.frame(unique(employers$Employer))

write.csv(employers,     file = "employers.csv")
write.csv(employersList, file = "employersList.csv")

test <- employers %>% 
  group_by(SOC, Employer) %>%
  tally  %>%
  group_by(Employer) 
